name: 'Get & Cached Dependencies'
description: 'Get the dependencies and cached'
runs: 
  using: 'composite'
  steps: 
    - name: Cache Dependency
      uses: actions/cache@v3
      with: 
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cahce-hit != true
      run: npm ci
      shell: bash