name: ArtiControllflow Project
on: workflow_dispatch
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        - name: Cache Dependency
          uses: actions/cache@v3
          with: 
            path: ~/.npm
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: 18
        #- name: Install dependendencies
         # run: npm ci
        - name: Run Test
          #run: npm test
          run: echo "Running Test"
  build:
    needs: test
    runs-on: ubuntu-latest
    #ouput key acessable later insi de
    outputs:
      script-file: ${{steps.publish.outputs.script-file}}
    steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Build website
          run: npm run build
        - name: Test COde
          run: npm run test
          id: run-test  
        - name: upload test report
          if: failure() && steps.run-test.outcome == 'failure'
          uses: actions/upload-artifact@v3
          with:
            name: dist-flies
            path: dist.json   
        - name: Deploy
          run: echo "Building"
  
  reprt:
    if: failure()
    runs-on: ubuntu-latest
    steps:
        - name: Output Information
          run: |
            echo "Something went wrong"
            echo "${{github}}"