name: Test Project
on:  [push, workflow_dispatch]
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: 18
        #- name: Install dependendencies
         # run: npm ci
        - name: Run Test
          #run: npm test
          run: echo "Running Test"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: 18
        #- name: Install dependendencies
         # run: npm ci
        #- name: Build Project
         # run: npm run build
        - name: Deploy
          run: echo "Deploying"

